query getList($id: ID){
  list(id: $id) {
    name
    isPublic
    owner
    items {
      id
      productId
      skuId
      quantity
      product{
        productId
        items {
          itemId
        }
      }
    }
  }
}
