query getListByOwner($owner: ID!) {
  listsByOwner(owner: $owner) @context(provider: "vtex.store-graphql") {
    id
    name
    isPublic
    isEditable
    owner
    items {
      id
      productId
      skuId
      quantity
    }
  }
}