query getListDetails($id: ID) {
  list(id: $id) {
    name
    items {
      product {
        linkText
        productName
        items {
          images {
            imageUrl
          }
          name
          itemId
          sellers {
            commertialOffer {
              ListPrice
              Price
            }
            sellerId
          }
        }
      }
    }
  }
}
