query getListDetails($id: ID) {
  list(id: $id) @context(provider: "vtex.store-graphql") {
    name
    isEditable
    isPublic
    items {
      id
      productId
      skuId
      quantity
      product {
        productId
        productName
        description
        categories
        link
        linkText
        brand
        items {
          name
          itemId
          referenceId {
            Value
          }
          images {
            imageUrl
            imageTag
          }
          sellers {
            sellerId
            commertialOffer {
              Installments {
                Value
                InterestRate
                TotalValuePlusInterestRate
                NumberOfInstallments
                Name
              }
              AvailableQuantity
              Price
              ListPrice
            }
          }
        }
        productClusters {
          id
          name
        }
      }
    }
  }
}
